### PR TITLE
⚓  Docker support added

### PR DESCRIPTION
**Pull request by Meldiron**
I have managed to get Boltz working in a docker. This is a draft pull request as a lot of stuff still needs to be done:

- Prepare a docker-compose and one-command startup
- Use environment variables instead of JSON configs
- Update README with a guide on how to use the Boltz in docker with multiple examples (port mapping, with Nginx, with traffic, persistent data, volumes, ...)

Right now, I need you to include `docker build` into the release flow and publish it automatically to the Docker hub, so we can start using it in the `docker.compose.yml` file.

### CODE REVIEW

**Comment by bsnk-dev** [comment]
Ok, I'll get that built and pushed to docker hub.

**Comment by bsnk-dev** [comment]
Ok, @Meldiron, you should be able to pull [bsnk/boltz-engine](https://hub.docker.com/r/bsnk/boltz-engine) from docker. I checked it on Cloud Shell and it looks like it works.

**Comment by Meldiron** [comment]
Great job! Thanks. Now, I would like to focus on environment variable configuration. Would it be okay if I wrote a logic that overrides configuration from `secrets.json` and `config.json` if environment variables are set? This would allow us to (for example) set admin credentials when starting a Docker container.

**Comment by bsnk-dev** [comment]
Of course! It makes a lot more sense for docker installations. Of course the option for people to deploy Boltz with its standard config file mounted to the app directory will work too.

**Pull request merged**
